[package]
name = "rikkadesk"
version = "0.1.0"
description = "An unofficial desktop derivative / experiment based on RikkaHub."
authors = ["Cisyam-x"]
edition = "2021"
license = "AGPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
